# Permalinks
permalink:        pretty
relative_permalinks: true

# Page list
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Setup
title:            vidcina
tagline:          my swift blog
url:              http://getpoole.com
comments:         True
paginate:         1
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
