# Permalinks
permalink:        pretty
relative_permalinks: true

# Page list
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Setup
title:            vidcina
tagline:          swift blog
url:              http://vidcina.github.io
comments:         True
paginate:         1
baseurl:          /
author:
  name:           vidcina
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/vidcina/vidcina.github.io
